apiVersion: apps/v1
kind: Deployment
metadata:
  name: jchurtado-deployment
  labels:
    app: jchurtadoapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jchurtadoapp
  template:
    metadata:
      labels:
        app: jchurtadoapp
    spec:
      containers:
      - name: jchurtado-container
        image: jchurtado/cicd:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: jchurtadoapp-lb
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: jchurtadoapp 
