#Workflow to deploy the artifacts

name: cd
on:
  workflow_run:
    workflows: ["ci"]
    types: 
      - completed
    

jobs:
  build: 
    runs-on: self-hosted
    environment: prod
    steps:
      - name: Checkout 
        uses: actions/checkout@v4.1.1
      - name: Deployment with Ansible
        run: |
          sudo ansible-playbook -i ./inv play.yml
     # - name: Deployment using Kubernetes
      #  run: |
       #   kubectl delete deployment jchurtado-deployment 
        #  kubectl apply -f deployment.yml
         # kubectl get deployment
        
