#Workflow to deploy the artifacts

name: cd
on:
  workflow_run:
    workflows: ["ci"]
    types: 
      - completed
    

jobs:
  build: 
    runs-on: self-hosted
    environment: prod
    steps:
      - name: Checkout 
        uses: actions/checkout@v4.1.1
      - name: Deployment using Kubernetes
        run: |
          kubectl apply -f deployment.yml
          kubectl get deployment
          
