#Workflow to build the environment

name: ci
on:
  push

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo on ubuntu runner
        uses: actions/checkout@v4.1.1
      - name: Install Java version 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'
      - name: Build with Maven
        run: |
          mvn package
          ls -l
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          name: devops-war
          path: target/devops.war
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: jchurtado/cicd:latest
          
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    needs: build
    steps:
      - name: download the artifact
        uses: actions/download-artifact@v4.0.0
        with:
          name: devops-war
          path: /tmp/
      - name: Display structure of downloaded files
        run: ls -l /tmp/
          
    
          #scp target/devops.war user:password@server/opt/tomcat/webapps/
          #ssh 
